### ISSUE TITLE
Location and address containing single quotes are only partially scraped

### ISSUE THREAD

**Issue by archived-m** [pietercolpaert/bluebike-scraper#5]
Example 1:

Original text: 
>The 'bike point' is in the train station. The key distributor and the bikes are towards platform 1.

Scraped:
>The 

Example 2: 

Original text: 
>Le point-vélo se trouve dans la gare. Pour l'instant seulement disponible entre 07.00 et 19.00 pendant la semaine.

Scraped:
>Le point-vélo se trouve dans la gare. Pour l

**Comment by pietercolpaert** [comment]
It’s a difficult one I’m afraid: the JSON that is scraped from the body of the HTML contains unicode characters that are converted in the JSON to normal characters. In the JSON, there is HTML again (ugh), but the unicode characters (indicated with \u...) are already converted and of course trigger the HTML entity to close earlier. It’s very particular how this actually works in the browser on their website... Not sure how to fix this one

**Comment by pietercolpaert** [comment]
This was fixed. Thanks @MichielLeyman and @julianrojas87 for your input!
